version: "3.8"

services:
  frontend:
    image: ${IMAGE_NAME}
    container_name: watchcash_frontend_prod
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
    restart: always