version: "3.8"

services:
  frontend:
    image: ${IMAGE}
    container_name: watchcash_frontend_dev
    ports:
      - "9000:3000"
    restart: always
    environment:
      - NODE_ENV=development