name: Build Push and Deploy

on:
  push:
    branches:
      - development   # change if using development
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/watchcashfront_repo:latest .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/watchcashfront_repo:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USER }}/watchcashfront_repo:latest
            echo "Stopping and removing existing container..."
            docker stop watchcashfront_repo || true
            docker rm watchcashfront_repo || true
            echo "Starting new container..."
            docker run -d \
              --name watchcashfront_repo \
              -p 9000:3000 \
              --restart=always \
              ${{ secrets.DOCKER_USER }}/watchcashfront_repo:latest
            echo "Deployment complete!"