name: Build Push and Deploy Dev

on:
  push:
    branches:
      - development
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --pull -t ${{ secrets.DOCKER_USER }}/watchcashfront_repo:devlatest .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/watchcashfront_repo:devlatest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          echo "Pulling latest image..."
          IMAGE="${{ secrets.DOCKER_USER }}/watchcashfront_repo:devlatest"
          ENV_PATH="${{ secrets.EC2_APP_PATH }}/.env"

          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
            echo "Pulling latest image..."
            docker pull $IMAGE

            docker stop watchcash_admin_dev || true
            docker rm watchcash_admin_dev || true

            docker run -d \
              --name watchcash_admin_dev \
              --env-file $ENV_PATH \
              -p 9000:3000 \
              --restart always \
              $IMAGE

            docker image prune -af || true
          EOF